version: '3'
services:
  bruschetta:
    build: .
    ports
      - "3000:3000"
    links:
      - database
    volumes:
      - uek:/var/lib/uek
    env_file:
      - ./credentials.env
    depends_on:
      - database
  database:
    restart: always
    image: postgres:alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./credentials.env
volumes:
  pgdata:
  uek:
