version: '3'
services:
  bruschetta:
    build: .
    ports:
      - "80:3000"
    links:
      - database
    env_file:
      - ./credentials.env
  database:
    restart: always
    image: postgres:alpine
    ports:
      - "5432:5432"
    env_file:
      - ./credentials.env
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql